_base_: ./hard_st_benchmark_b_v2_teacher1201_pinit_prefix_12713_13111_readout9505_cmix_fq4_selectproxy_src13111_delayed_lw01375_start024_stop072_llr.yaml

experiment:
  seed: 14512

teacher:
  scale_start: 1.0
  scale_end: 0.25
